<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b9759db1-0f48-4554-8c59-70b2fc962e66</elementGuidId>
    <imagePath></imagePath>
    <name>button_switchToDarkMode</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/div[2]/div[1]/button[5]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text=/^HomeBlogResumeContact$/ &gt;&gt; internal:label=\"Switch to dark mode\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>