<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Regression Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bb9d9050-8502-4f75-bd0c-b78a31645c86</testSuiteGuid>
   <testCaseLink>
      <guid>49077fd2-380b-4613-a25c-6eb774800571</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC1-Send Message and Toggle Blog Modes on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f24bcdd3-6819-489c-bfa0-62d78e104063</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83899156-3d42-4e10-ac98-b5c6c3d61e6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0362c14-a88c-4513-8b4e-a5801d0ec6d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bf36524-0eeb-42a5-a95f-fbc7119d45e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC10-Schedule Call and Access LinkedIn on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>848c21a4-ced9-4780-b5c8-8126591745a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC11-Navigate Blog and Academic Journey on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcaf5cb0-ee29-4085-a99c-aa94b5b382ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1753bd07-749d-49fc-96a2-87b917c29bbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5bd737f-983d-4e48-9899-cec9660d2a22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC12-View Resume and Project Coordination on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>691ef764-b858-4839-8ff9-09c468cf4ae1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC13-View Comprehensive Resume and Profile on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b469b4a-6ca0-496f-874f-05babe63affa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6f8a268-5284-411e-984d-fbfa9a9c338b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>317b4470-0fde-43c8-bee9-99587f4f6770</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2f9cc99-1fc5-47cd-80ae-47346f476471</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC2-Access Social Media Links from Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cb6f860f-bad8-46e7-8516-feb69affbb84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC3-Schedule Call and Fill Contact Form on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ca558c98-d9ec-4ca0-8b79-cd5fbe6b2632</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC4-Explore Projects and Access Blog on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d3b7a88-e144-4389-b974-c121543f3a34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d420420-30e5-43f2-88c2-ac154762f36c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d5f9e0f-4eca-4a69-a794-798fdbf0d5c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4789a130-338f-4bb6-9cba-42740311c64f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC5-View Skills and Contact Information on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ade7b88b-4ce6-44d8-bbc3-70c19e774bbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC6-Send Message and Access Blog from Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ce3e2f1e-7787-472d-b403-d57b9fc14b72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC7-Explore Portfolio Projects on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bda6ed4f-88d8-48c8-b9d6-0293fda61b67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC8-Explore Skills and Resume on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d55beadf-7a86-4cdf-99ad-465a7f5ca3e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC9-Navigate Resume and Contact Form on Portfolio Web</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d13411a8-ad7d-4325-b269-224e836d21db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02f7560a-fb61-43ca-8f12-6e289756ebad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b646fa4b-e739-4947-8cea-412391dc6ba4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91e5e6c6-54ec-4db5-8592-06cdc601406e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c159eec9-5311-4815-bb6d-48bb4af3ee8c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
