<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>925e44d9-e430-4976-ab40-85e761d62590</elementGuidId>
    <imagePath></imagePath>
    <name>span_dynamicObject</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[5]/div[6]/div[1]/div[1]/div[1]/div[2]/span[1]/span[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span:nth-child(${span_dynamicObject_spanNthChild}) &gt; span:nth-child(${span_dynamicObject_spanNthChild_1})</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>