<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>97e0ece8-b306-4476-95f9-7087e3225c14</elementGuidId>
    <imagePath></imagePath>
    <name>input_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'name') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder=\"Your name\"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>name</value>
        <webElementGuid>bc0383fb-5e71-4507-91d0-d6a27101bc30</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>bc0383fb-5e71-4507-91d0-d6a27101bc30</webElementGuid>
    </webElementProperties>
</WebElementEntity>