<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8ef93412-b180-4da5-a245-5daed7b06c52</elementGuidId>
    <imagePath></imagePath>
    <name>span_object3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[5]/div[6]/div[1]/div[1]/div[1]/div[1]/span[14]/span[9]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span:nth-child(14) &gt; span:nth-child(9) &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>